// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace forumDB.Model
{
    public partial class Curso
    {
        public Curso()
        {
            Pergunta = new HashSet<Pergunta>();
            Usuario = new HashSet<Usuario>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        [Unicode(false)]
        [DisplayName("Curso")]
        public string Nome { get; set; }

        [InverseProperty("IdCursoNavigation")]
        public virtual ICollection<Pergunta> Pergunta { get; set; }
        [InverseProperty("IdCursoNavigation")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}