// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace forumDB.Model
{
    public partial class Resposta
    {
        public Resposta()
        {
            Denuncia = new HashSet<Denuncia>();
            Nota = new HashSet<Nota>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("id_pergunta")]
        public int? IdPergunta { get; set; }
        [Column("id_usuario")]
        public int? IdUsuario { get; set; }
        [Column("texto")]
        [StringLength(255)]
        [Unicode(false)]
        public string Texto { get; set; }
        [Column("horario", TypeName = "datetime")]
        public DateTime? Horario { get; set; }

        [ForeignKey("IdPergunta")]
        [InverseProperty("Resposta")]
        public virtual Pergunta IdPerguntaNavigation { get; set; }
        [ForeignKey("IdUsuario")]
        [InverseProperty("Resposta")]
        public virtual Usuario IdUsuarioNavigation { get; set; }
        [InverseProperty("IdRespostaNavigation")]
        public virtual ICollection<Denuncia> Denuncia { get; set; }
        [InverseProperty("IdRespostaNavigation")]
        public virtual ICollection<Nota> Nota { get; set; }
    }
}