// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace forumDB.Model
{
    public partial class Usuario
    {
        public Usuario()
        {
            Denuncia = new HashSet<Denuncia>();
            Nota = new HashSet<Nota>();
            Pergunta = new HashSet<Pergunta>();
            Resposta = new HashSet<Resposta>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("matricula")]
        [StringLength(10)]
        [Unicode(false)]
        public string Matricula { get; set; }
        [Column("id_curso")]
        public int IdCurso { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("email")]
        [StringLength(150)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(255)]
        [Unicode(false)]
        public string Senha { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Foto { get; set; }
        [Column("administrador")]
        public bool? Administrador { get; set; }

        [ForeignKey("IdCurso")]
        [InverseProperty("Usuario")]
        public virtual Curso IdCursoNavigation { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Denuncia> Denuncia { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Nota> Nota { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Pergunta> Pergunta { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<Resposta> Resposta { get; set; }
    }
}